title: <p align="center">Bindu GK </p>
logo: /assets/img/logo.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/Bindugk18/">LinkedIn</a> |
  <a href="https://github.com/Bindugk4">GitHub</a>
  
  <br>   
  Persuing diplomo in Machine learning and artificial inteligence
  <br>
  </p>



theme: jekyll-theme-minimal
